apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-approuter-deployment
  namespace: socmiddleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-approuter
  template:
    metadata:
      labels:
        app: my-approuter
    spec:
      containers:
      - name: my-approuter
        image: devx-research.common.repositories.cloud.sap/saggir/approuter:0.1.8
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: docker-pull-secret-devx-research

---
apiVersion: v1
kind: Service
metadata:
  name: my-approuter-service
  namespace: socmiddleware
spec:
  type: ClusterIP
  selector:
    app: my-approuter
  ports:
    - port: 5000
      targetPort: 5000


